*&---------------------------------------------------------------------*
*& Report ZEDR20_001
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZEDR20_015.

" DATA : GS_STUDENT TYPE ZEDT20_001.
DATA : BEGIN OF GS_STUDENT,
        ZPERNR TYPE ZEDT20_001-ZPERNR,
        ZCODE TYPE ZEDT20_001-ZCODE,
        ZKNAME TYPE ZEDT20_001-ZKNAME,
        ZENAME TYPE ZEDT20_001-ZENAME,
        ZGENDER TYPE ZEDT20_001-ZGENDER,
        ZTEL TYPE ZEDT20_001-ZTEL,
        ZGNAME(10) TYPE C,
      END OF GS_STUDENT.
DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.

CLEAR : GS_STUDENT, GT_STUDENT.

GS_STUDENT-ZPERNR = '0000000001'.
GS_STUDENT-ZCODE = 'SSU-01'.
GS_STUDENT-ZKNAME = '강동원'.
GS_STUDENT-ZENAME = 'DONG'.
GS_STUDENT-ZGENDER = 'M'.
GS_STUDENT-ZTEL = '01011112222'.
APPEND GS_STUDENT TO GT_STUDENT.

GS_STUDENT-ZPERNR = '0000000001'.
GS_STUDENT-ZCODE = 'SSU-01'.
GS_STUDENT-ZKNAME = '강동원'.
GS_STUDENT-ZENAME = 'DONG'.
GS_STUDENT-ZGENDER = 'M'.
GS_STUDENT-ZTEL = '01011112223'.
APPEND GS_STUDENT TO GT_STUDENT.

CLEAR : GS_STUDENT.
GS_STUDENT-ZPERNR = '0000000002'.
GS_STUDENT-ZCODE = 'SSU-02'.
GS_STUDENT-ZKNAME = '이제훈'.
GS_STUDENT-ZENAME = 'HOON'.
GS_STUDENT-ZGENDER = 'M'.
GS_STUDENT-ZTEL = '01022223333'.
APPEND GS_STUDENT TO GT_STUDENT.

CLEAR : GS_STUDENT.

SORT GT_STUDENT.

LOOP AT GT_STUDENT INTO GS_STUDENT.
  GS_STUDENT-ZGNAME = '성별구분'.

  AT FIRST.
    GS_STUDENT-ZGNAME = '변경사항'.
  ENDAT.

  CLEAR GS_STUDENT.
ENDLOOP.

LOOP AT GT_STUDENT INTO GS_STUDENT.
  WRITE :/ GS_STUDENT-ZCODE, GS_STUDENT-ZKNAME, GS_STUDENT-ZENAME, GS_STUDENT-ZGNAME.
ENDLOOP.