*&---------------------------------------------------------------------*
*& Report ZEDR20_015
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZEDR20_015.


DATA : BEGIN OF GS_STUDENT,
  ZPERNR LIKE ZEDT00_001-ZPERNR, "출석번호
  ZCODE LIKE ZEDT00_001-ZCODE, "학생코드
  ZKNAME LIKE ZEDT00_001-ZKNAME, "이름
  ZENAME LIKE ZEDT00_001-ZENAME, "영문명
  ZGENDER LIKE ZEDT00_001-ZGENDER, "성별
  ZGNAME TYPE C LENGTH 8, "성별구분
  ZTEL LIKE ZEDT00_001-ZTEL, "전화번호
  END OF GS_STUDENT.
DATA : GS_STUDENT2 LIKE GS_STUDENT.
DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.

DATA : LV_END. "AT구문 적용변수


CLEAR : GS_STUDENT, GT_STUDENT.
GS_STUDENT-ZPERNR = '0000000001'.
GS_STUDENT-ZCODE = 'SSU-01'.
GS_STUDENT-ZKNAME = '강동원'.
GS_STUDENT-ZENAME = 'DONG'.
GS_STUDENT-ZGENDER = 'M'.
GS_STUDENT-ZTEL = '01011112222'.
APPEND GS_STUDENT TO GT_STUDENT.

CLEAR : GS_STUDENT.
GS_STUDENT-ZPERNR = '0000000001'.
GS_STUDENT-ZCODE = 'SSU-01'.
GS_STUDENT-ZKNAME = '강동원'.
GS_STUDENT-ZENAME = 'DONG'.
GS_STUDENT-ZGENDER = 'F'.
GS_STUDENT-ZTEL = '01011112222'.
APPEND GS_STUDENT TO GT_STUDENT.

CLEAR : GS_STUDENT.
GS_STUDENT-ZPERNR = '0000000001'.
GS_STUDENT-ZCODE = 'SSU-01'.
GS_STUDENT-ZKNAME = '강동원'.
GS_STUDENT-ZENAME = 'DONG'.
GS_STUDENT-ZGENDER = 'A'.
GS_STUDENT-ZTEL = '01011112222'.
APPEND GS_STUDENT TO GT_STUDENT.

CLEAR : GS_STUDENT.
GS_STUDENT-ZPERNR = '0000000002'.
GS_STUDENT-ZCODE = 'SSU-02'.
GS_STUDENT-ZKNAME = '이제훈'.
GS_STUDENT-ZENAME = 'LEE'.
GS_STUDENT-ZGENDER = 'M'.
GS_STUDENT-ZTEL = '01022223333'.
APPEND GS_STUDENT TO GT_STUDENT.

CLEAR : GS_STUDENT.
GS_STUDENT-ZPERNR = '0000000001'.
GS_STUDENT-ZCODE = 'SSU-01'.
GS_STUDENT-ZKNAME = '강동원'.
GS_STUDENT-ZENAME = 'KANG'.
GS_STUDENT-ZGENDER = 'M'.
GS_STUDENT-ZTEL = '01011112222'.
APPEND GS_STUDENT TO GT_STUDENT.

CLEAR : GS_STUDENT.
GS_STUDENT-ZPERNR = '0000000001'.
GS_STUDENT-ZCODE = 'SSU-01'.
GS_STUDENT-ZKNAME = '강동동'.
GS_STUDENT-ZENAME = 'DONG'.
GS_STUDENT-ZGENDER = 'F'.
GS_STUDENT-ZTEL = '01011112222'.
APPEND GS_STUDENT TO GT_STUDENT.

CLEAR : GS_STUDENT, GS_STUDENT2.
SORT GT_STUDENT BY ZCODE ZKNAME ZENAME ZGENDER.

"버전0 . 그냥 실행해보기(논리적 에러)
LOOP AT GT_STUDENT INTO GS_STUDENT.
  GS_STUDENT-ZGNAME = '성별구분'.

  AT END OF ZENAME.
    GS_STUDENT-ZGNAME = '변경사항'.
  ENDAT.

  MODIFY GT_STUDENT FROM GS_STUDENT INDEX SY-TABIX.
ENDLOOP.

*"버전1 . move-corresponging 사용
*LOOP AT GT_STUDENT INTO GS_STUDENT.
*  GS_STUDENT-ZGNAME = '성별구분'.
*  MOVE-CORRESPONDING GS_STUDENT TO GS_STUDENT2.
*
*  AT END OF ZENAME.
*    GS_STUDENT2-ZGNAME = '변경사항'.
*  ENDAT.
*
*  MODIFY GT_STUDENT FROM GS_STUDENT2 INDEX SY-TABIX.
*
*  CLEAR : GS_STUDENT, GS_STUDENT2.
*ENDLOOP.

*"버전2 . L_로컬변수 사용
*LOOP AT GT_STUDENT INTO GS_STUDENT.
*  CLEAR : LV_END.
*  GS_STUDENT-ZGNAME = '성별구분'.
*
*  AT END OF ZENAME.
*    LV_END = 'X'.
*    GS_STUDENT2-ZGNAME = '변경사항'.
*  ENDAT.
*
*  IF LV_END = 'X'.
*    GS_STUDENT-ZGNAME = '변경사항'.
*  ENDIF.
*
*  MODIFY GT_STUDENT FROM GS_STUDENT INDEX SY-TABIX.
*  CLEAR : GS_STUDENT.
*ENDLOOP.

LOOP AT GT_STUDENT INTO GS_STUDENT.
  WRITE :/ GS_STUDENT-ZCODE, GS_STUDENT-ZKNAME, GS_STUDENT-ZENAME, GS_STUDENT-ZGNAME.
ENDLOOP.