IF S_ZCODE IS INITIAL.
    MESSAGE I000.
ENDIF.

"INITIAL : 초기값을 의미한다. 즉, S_ZCODE가 초기값이면 메시지 I000을 출력한다.

*&---------------------------------------------------------------------*
*& Report ZEDR20_23
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZEDR20_23 MESSAGE-ID ZMED20.

TABLES : ZEDT20_001.

DATA : BEGIN OF GS_STUDENT.
  INCLUDE TYPE ZEDT20_001.
  DATA : END OF GS_STUDENT.
DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.
  SELECT-OPTIONS : S_ZCODE FOR ZEDT20_001-ZCODE.
  PARAMETERS : P_ZPERNR LIKE ZEDT20_001-ZPERNR.
  PARAMETERS : P_ZGEN LIKE ZEDT20_001-ZGENDER.
SELECTION-SCREEN END OF BLOCK B1.

IF S_ZCODE IS INITIAL.
  MESSAGE I000.
    EXIT.
ENDIF.

PERFORM GET_DATA USING S_ZCODE. "

IF GT_STUDENT IS INITIAL.
  MESSAGE I001.
  EXIT.
ENDIF.

PERFORM WRITE_DATA.

FORM GET_DATA USING P_ZCODE.

*  "SELECT 인터널테이블
*  SELECT SINGLE ZKNAME FROM ZEDT20_001
*    INTO GS_STUDENT-ZKNAME
*    WHERE ZCODE = P_ZCODE.
*    APPEND GS_STUDENT TO GT_STUDENT.

  WRITE :/ 'IN GET_DAT'.
ENDFORM.

FORM WRITE_DATA.
  WRITE :/ 'IN WRITE_DATA'.
ENDFORM.