REPORT ZEDR20_PRACTICE002.


DATA : BEGIN OF GS_ZEDT001.
INCLUDE TYPE ZEDT00_001.
DATA : ZMAJOR_MEMO(8).
DATA : ZGRADE_MEMO(8).
DATA : END OF GS_ZEDT001.

DATA : BEGIN OF GS_ZEDT002.
  INCLUDE TYPE ZEDT00_002.
DATA : END OF GS_ZEDT002.

DATA : BEGIN OF GS_ZEDT003.
  INCLUDE TYPE ZEDT00_003.
DATA : END OF GS_ZEDT003.

DATA : GT_ZEDT001 LIKE TABLE OF GS_ZEDT001.
DATA : GT_ZEDT002 LIKE TABLE OF GS_ZEDT002.
DATA : GT_ZEDT003 LIKE TABLE OF GS_ZEDT003.

DATA : BEGIN OF GS_GENDERSUM,
  ZGENDER LIKE ZEDT00_001-ZGENDER,
  ZGENDERSUM LIKE ZEDT00_002-ZSUM,
END OF GS_GENDERSUM.

DATA : GT_GENDERSUM LIKE TABLE OF GS_GENDERSUM.


"변수
DATA : GV_LINE TYPE I.
DATA : GV_SUM TYPE I.


"2. GET DATA
SELECT * FROM ZEDT00_001
INTO CORRESPONDING FIELDS OF TABLE GT_ZEDT001.

SELECT * FROM ZEDT00_002
INTO CORRESPONDING FIELDS OF TABLE GT_ZEDT002.

SELECT * FROM ZEDT00_003
INTO CORRESPONDING FIELDS OF TABLE GT_ZEDT003.

SORT GT_ZEDT001 BY ZCODE ASCENDING.
SORT GT_ZEDT002 BY ZCODE ASCENDING.
SORT GT_ZEDT003 BY ZCODE ASCENDING ZGRADE DESCENDING.

