
FORM FIELD_CATALOG2 .

  CLEAR : GS_FIELDCAT_ITEM, GT_FIELDCAT_ITEM.
  GS_FIELDCAT_ITEM-COL_POS = 1.
  GS_FIELDCAT_ITEM-FIELDNAME = 'EBELN'.
  GS_FIELDCAT_ITEM-COLTEXT = 'PO번호'.
  APPEND GS_FIELDCAT_ITEM TO GT_FIELDCAT_ITEM.

  CLEAR : GS_FIELDCAT_ITEM.
  GS_FIELDCAT_ITEM-COL_POS = 2.
  GS_FIELDCAT_ITEM-FIELDNAME = 'EBELP'.
  GS_FIELDCAT_ITEM-COLTEXT = '품목'.
  APPEND GS_FIELDCAT_ITEM TO GT_FIELDCAT_ITEM.
  
  CLEAR : GS_FIELDCAT_ITEM.
  GS_FIELDCAT_ITEM-COL_POS = 3.
  GS_FIELDCAT_ITEM-FIELDNAME = 'ZMATNR'.
  GS_FIELDCAT_ITEM-COLTEXT = '자재번호'.
  APPEND GS_FIELDCAT_ITEM TO GT_FIELDCAT_ITEM.
  
  CLEAR : GS_FIELDCAT_ITEM.
  GS_FIELDCAT_ITEM-COL_POS = 4.
  GS_FIELDCAT_ITEM-FIELDNAME = 'ZMATNAME'.
  GS_FIELDCAT_ITEM-COLTEXT = '자재명'.
  APPEND GS_FIELDCAT_ITEM TO GT_FIELDCAT_ITEM.
  
  CLEAR : GS_FIELDCAT_ITEM.
  GS_FIELDCAT_ITEM-COL_POS = 5.
  GS_FIELDCAT_ITEM-FIELDNAME = 'MMENGE'.
  GS_FIELDCAT_ITEM-COLTEXT = 'PO수량'.
  APPEND GS_FIELDCAT_ITEM TO GT_FIELDCAT_ITEM.
  
  CLEAR : GS_FIELDCAT_ITEM.
  GS_FIELDCAT_ITEM-COL_POS = 6.
  GS_FIELDCAT_ITEM-FIELDNAME = 'STPRS'.
  GS_FIELDCAT_ITEM-COLTEXT = '단가'.
  APPEND GS_FIELDCAT_ITEM TO GT_FIELDCAT_ITEM.
  
  CLEAR : GS_FIELDCAT_ITEM.
  GS_FIELDCAT_ITEM-COL_POS = 7.
  GS_FIELDCAT_ITEM-FIELDNAME = 'ZMEINS'.
  GS_FIELDCAT_ITEM-COLTEXT = '단위'.
  APPEND GS_FIELDCAT_ITEM TO GT_FIELDCAT_ITEM.
  
  CLEAR : GS_FIELDCAT_ITEM.
  GS_FIELDCAT_ITEM-COL_POS = 8.
  GS_FIELDCAT_ITEM-FIELDNAME = 'PRDAT'.
  GS_FIELDCAT_ITEM-COLTEXT = '납품일'.
  APPEND GS_FIELDCAT_ITEM TO GT_FIELDCAT_ITEM.
  
  CLEAR : GS_FIELDCAT_ITEM.
  GS_FIELDCAT_ITEM-COL_POS = 9.
  GS_FIELDCAT_ITEM-FIELDNAME = 'ZWERKS'.
  GS_FIELDCAT_ITEM-COLTEXT = '플랜트'.
  APPEND GS_FIELDCAT_ITEM TO GT_FIELDCAT_ITEM.
  
  CLEAR : GS_FIELDCAT_ITEM.
  GS_FIELDCAT_ITEM-COL_POS = 10.
  GS_FIELDCAT_ITEM-FIELDNAME = 'ZLGORT'.
  GS_FIELDCAT_ITEM-COLTEXT = '저장위치'.
  APPEND GS_FIELDCAT_ITEM TO GT_FIELDCAT_ITEM.
  
  ENDFORM.