CLEAR : GS_FIELDCAT_MAT , GT_FIELDCAT_MAT.

GS_FIELDCAT_MAT-COL_POS = 1.
GS_FIELDCAT_MAT-FIELDNAME = 'ZMATNR'.
GS_FIELDCAT_MAT-COLTEXT = '제품번호'.
APPEND GS_FIELDCAT_MAT TO GT_FIELDCAT_MAT.

CLEAR : GS_FIELDCAT_MAT.
GS_FIELDCAT_MAT-COL_POS = 2.
GS_FIELDCAT_MAT-FIELDNAME = 'ZMATNAME'.
GS_FIELDCAT_MAT-COLTEXT = '제품명'.
APPEND GS_FIELDCAT_MAT TO GT_FIELDCAT_MAT.

CLEAR : GS_FIELDCAT_MAT.
GS_FIELDCAT_MAT-COL_POS = 3.
GS_FIELDCAT_MAT-FIELDNAME = 'ZWERKS'.
GS_FIELDCAT_MAT-COLTEXT = '플랜트명'.
APPEND GS_FIELDCAT_MAT TO GT_FIELDCAT_MAT.

CLEAR : GS_FIELDCAT_MAT.
GS_FIELDCAT_MAT-COL_POS = 4.
GS_FIELDCAT_MAT-FIELDNAME = 'ZLGORT'.
GS_FIELDCAT_MAT-COLTEXT = '저장위치명'.
APPEND GS_FIELDCAT_MAT TO GT_FIELDCAT_MAT.

CLEAR : GS_FIELDCAT_MAT.
GS_FIELDCAT_MAT-COL_POS = 5.
GS_FIELDCAT_MAT-FIELDNAME = 'ZMTART'.
GS_FIELDCAT_MAT-COLTEXT = '자재유형명'.
APPEND GS_FIELDCAT_MAT TO GT_FIELDCAT_MAT.

CLEAR : GS_FIELDCAT_MAT.
GS_FIELDCAT_MAT-COL_POS = 6.
GS_FIELDCAT_MAT-FIELDNAME = 'STPRS'.
GS_FIELDCAT_MAT-COLTEXT = '단가'.
APPEND GS_FIELDCAT_MAT TO GT_FIELDCAT_MAT.

CLEAR : GS_FIELDCAT_MAT.
GS_FIELDCAT_MAT-COL_POS = 7.
GS_FIELDCAT_MAT-FIELDNAME = 'WAERS'.
GS_FIELDCAT_MAT-COLTEXT = '통화'.
APPEND GS_FIELDCAT_MAT TO GT_FIELDCAT_MAT.

CLEAR : GS_FIELDCAT_MAT.
GS_FIELDCAT_MAT-COL_POS = 8.
GS_FIELDCAT_MAT-FIELDNAME = 'MENGE'.
GS_FIELDCAT_MAT-COLTEXT = '수량'.
APPEND GS_FIELDCAT_MAT TO GT_FIELDCAT_MAT.

CLEAR : GS_FIELDCAT_MAT.
GS_FIELDCAT_MAT-COL_POS = 9.
GS_FIELDCAT_MAT-FIELDNAME = 'MEINS'.
GS_FIELDCAT_MAT-COLTEXT = '단위'.
APPEND GS_FIELDCAT_MAT TO GT_FIELDCAT_MAT.