FORM FIELD_CATALOG .
    CLEAR : GS_FIELDCAT2, GT_FIELDCAT2.
    GS_FIELDCAT2-COL_POS = 1.
    GS_FIELDCAT2-FIELDNAME = 'ZLFA1_LIFNR'.
    GS_FIELDCAT2-COLTEXT = '구매처번호'.
    APPEND GS_FIELDCAT2 TO GT_FIELDCAT2.
  
  
    CLEAR : GS_FIELDCAT2.
    GS_FIELDCAT2-COL_POS = 3.
    GS_FIELDCAT2-FIELDNAME = 'ZLFA1_KTOKK'.
    GS_FIELDCAT2-COLTEXT = '구매처그룹'.
    APPEND GS_FIELDCAT2 TO GT_FIELDCAT2.
  
    CLEAR : GS_FIELDCAT2.
    GS_FIELDCAT2-COL_POS = 4.
    GS_FIELDCAT2-FIELDNAME = 'ZLFA1_NAME1'.
    GS_FIELDCAT2-COLTEXT = '구매처명'.
    GS_FIELDCAT2-EDIT = 'X'.
    APPEND GS_FIELDCAT2 TO GT_FIELDCAT2.
  
    CLEAR : GS_FIELDCAT2.
    GS_FIELDCAT2-COL_POS = 5.
    GS_FIELDCAT2-FIELDNAME = 'ZLFA1_LAND1'.
    GS_FIELDCAT2-COLTEXT = '국가키'.
    GS_FIELDCAT2-EDIT = 'X'.
    APPEND GS_FIELDCAT2 TO GT_FIELDCAT2.
  
    CLEAR : GS_FIELDCAT2.
    GS_FIELDCAT2-COL_POS = 6.
    GS_FIELDCAT2-FIELDNAME = 'ZLFA1_STCD1'.
    GS_FIELDCAT2-COLTEXT = '개인번호'.
    GS_FIELDCAT2-EDIT = 'X'.
  
    " 계정그룹 3000클릭시만 개인번호(LFA1-STCD1)필드가 보여야 하며
    IF P_KTOKK <> '3000'.
      GS_FIELDCAT2-NO_OUT = 'X'.
    ENDIF.
  
    APPEND GS_FIELDCAT2 TO GT_FIELDCAT2.
  
    CLEAR : GS_FIELDCAT2.
    GS_FIELDCAT2-COL_POS = 7.
    GS_FIELDCAT2-FIELDNAME = 'ZLFA1_STCD2'.
    GS_FIELDCAT2-COLTEXT = '사업자번호'.
    GS_FIELDCAT2-EDIT = 'X'.
    APPEND GS_FIELDCAT2 TO GT_FIELDCAT2.
  
    CLEAR : GS_FIELDCAT2.
    GS_FIELDCAT2-COL_POS = 8.
    GS_FIELDCAT2-FIELDNAME = 'ZLFA1_STRAS'.
    GS_FIELDCAT2-COLTEXT = '주소'.
    GS_FIELDCAT2-EDIT = 'X'.
    APPEND GS_FIELDCAT2 TO GT_FIELDCAT2.
  
  ENDFORM.