*&---------------------------------------------------------------------*
*& Report ZEDR20_PRACTICE002
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZEDR20_PRACTICE002.

DATA : GS_STUDENT TYPE ZEDT20_001.
DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT.

DATA : BEGIN OF GS_MAJOR,
      ZCODE LIKE ZEDT20_001-ZCODE,
      ZPERNR LIKE ZEDT20_001-ZPERNR,
      ZKNAME LIKE ZEDT20_001-ZKNAME,
      ZMNAME LIKE ZEDT20_002-ZMNAME,
      END OF GS_MAJOR.
DATA : GT_MAJOR LIKE TABLE OF GS_MAJOR WITH NON-UNIQUE KEY ZCODE.

CLEAR : GS_MAJOR, GT_MAJOR.
CLEAR : GS_STUDENT, GT_STUDENT.

GS_STUDENT-ZPERNR = '0000000001'.
GS_STUDENT-ZCODE = 'SSU-01'.
*GS_STUDENT-ZKNAME = '강동원'.
GS_STUDENT-ZENAME = 'DONG'.
GS_STUDENT-ZGENDER = 'M'.
GS_STUDENT-ZTEL = '01011112222'.
APPEND GS_STUDENT TO GT_STUDENT.

GS_MAJOR-ZPERNR = '0000000001'.
GS_MAJOR-ZKNAME = '강동원'.
GS_MAJOR-ZCODE = 'SSU-01'.
GS_MAJOR-ZMNAME = '경영학과'.
APPEND GS_MAJOR TO GT_MAJOR.

BREAK-POINT.


LOOP AT GT_STUDENT INTO GS_STUDENT.
  CLEAR : GS_MAJOR.
  MOVE-CORRESPONDING GS_STUDENT TO GS_MAJOR.

  READ TABLE GT_MAJOR INTO GS_MAJOR INDEX SY-TABIX.


  IF SY-SUBRC = 0.
    GS_STUDENT-ZKNAME = GS_MAJOR-ZKNAME.
    WRITE : / GS_STUDENT-ZCODE, GS_STUDENT-ZKNAME, GS_MAJOR-ZMNAME.
  ELSE.
    WRITE : / '데이터를 가져오지 못했습니다.'.
  ENDIF.
ENDLOOP.

BREAK-POINT.